app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
admin_routing:
    resource: "routing_admin.yml"
all_articles:
    path: /articles
    defaults: {_controller: AppBundle:Article:getAllArticles}
one_article:
     path: /article/{menu}/{id}{slug}
     defaults: {_controller: AppBundle:Article:getArticle}
     requirements:
        id : \d+
articles_by_menu:
      path: /articles/{id}_{title}
      defaults: {_controller: AppBundle:Article:getArticlesByMenu}
      requirements:
              id : \d+